language: node_js

dist: focal

node_js:
  - '18'

cache:
  npm: false
  yarn: false

before_install:
  - pip install awscli --upgrade --user
  - aws --version

install:
  - yarn
  - yarn build

script:
  - mkdir prerender-next&&for i in `ls -a|tail -n +5 |grep -v prerender-next`; do mv $i prerender-next/ ; done
  - aws ecr get-login --no-include-email --region us-east-1
  - docker build . -t prerender-next
  - docker images
  - env

