sudo: required
language:  node_js
node_js:
  - "18.18"

services:
  - docker

before_install:
  - npm config set progress false
  - npm install --global yarn
  - yarn --version

install:
  - yarn
  - yarn bulid


script: "pwd && ls"

