name: prerender-next
roleName: eks-us-east-1-prerender-next
hpa:
  enabled: true

container:
  port: 3000
  healthPath: /

readinessProbe:
  initialDelaySeconds: 30

livenessProbe:
  initialDelaySeconds: 30

ingress:
  enabled: true
  networkType:
    - internet-facing
  names:
    - "prerender-next"

rbac:
  enabled: false

workload: services

datadog:
  enabled: false

pdb:
  enabled: true
